export const CATEGORIES = [
  { id: 'focus', label: 'Focus', subtitle: 'attention & breath', color: '#8b5cf6' },
  { id: 'memory', label: 'Memory', subtitle: 'recall & sequence', color: '#f5a962' },
  { id: 'calm', label: 'Calm', subtitle: 'mindfulness & reflection', color: '#7fd67f' },
  { id: 'sharpness', label: 'Sharpness', subtitle: 'quick cognitive puzzles', color: '#f5d76e' },
]

export const GAMES = [
  {
    id: 'breath-pacer',
    name: 'Breath Pacer',
    category: 'focus',
    duration: '2 min',
    durationSec: 120,
    engine: 'BreathingOrb',
    description: 'Grow and shrink with the orb.',
    props: { variant: 'orb', inhale: 4, holdIn: 4, exhale: 4, holdOut: 4 },
  },
  {
    id: 'focus-dot',
    name: 'Focus Dot',
    category: 'focus',
    duration: '2 min',
    durationSec: 120,
    engine: 'FocusDot',
    description: 'Track the drifting dot with your eyes.',
    props: { variant: 'track' },
  },
  {
    id: 'sustained-attention',
    name: 'Sustained Attention',
    category: 'focus',
    duration: '2 min',
    durationSec: 120,
    engine: 'FocusDot',
    description: 'Tap only when the color changes.',
    props: { variant: 'color-change' },
  },
  {
    id: 'ocean-breath',
    name: 'Ocean Breath',
    category: 'focus',
    duration: '2 min',
    durationSec: 120,
    engine: 'BreathingOrb',
    description: 'Ride a slow wave of inhale and exhale.',
    props: { variant: 'wave', inhale: 4, holdIn: 2, exhale: 6, holdOut: 0 },
  },
  {
    id: 'pattern-recall',
    name: 'Pattern Recall',
    category: 'memory',
    duration: '2 min',
    durationSec: 120,
    engine: 'PatternRecall',
    description: 'Watch the tiles, then repeat the sequence.',
    props: { variant: 'tiles' },
  },
  {
    id: 'card-flip-match',
    name: 'Card Flip Match',
    category: 'memory',
    duration: '2 min',
    durationSec: 120,
    engine: 'CardMatch',
    description: 'Find the matching pairs.',
  },
  {
    id: 'number-recall',
    name: 'Number Recall',
    category: 'memory',
    duration: '2 min',
    durationSec: 120,
    engine: 'NumberRecall',
    description: 'Hold a growing number in mind.',
  },
  {
    id: 'face-position',
    name: 'Face-Position Memory',
    category: 'memory',
    duration: '2 min',
    durationSec: 120,
    engine: 'PatternRecall',
    description: 'Which face moved?',
    props: { variant: 'moved' },
  },
  {
    id: 'gratitude-prompt',
    name: 'Gratitude Prompt',
    category: 'calm',
    duration: '2 min',
    durationSec: 120,
    engine: 'TextPrompt',
    description: 'Name one small good thing.',
    props: { variant: 'gratitude' },
  },
  {
    id: 'thought-unload',
    name: 'Thought Unload',
    category: 'calm',
    duration: '2 min',
    durationSec: 120,
    engine: 'TextPrompt',
    description: 'Write it down, then let it go.',
    props: { variant: 'unload' },
  },
  {
    id: 'grounding-54321',
    name: '5-4-3-2-1 Grounding',
    category: 'calm',
    duration: '3 min',
    durationSec: 180,
    engine: 'TextPrompt',
    description: 'Come back to the room, one sense at a time.',
    props: { variant: 'grounding' },
  },
  {
    id: 'body-scan',
    name: 'Body Scan',
    category: 'calm',
    duration: '3 min',
    durationSec: 180,
    engine: 'BodyScan',
    description: 'Relax each part of the body in turn.',
  },
  {
    id: 'stroop-test',
    name: 'Stroop Test',
    category: 'sharpness',
    duration: '1 min',
    durationSec: 60,
    engine: 'StroopTest',
    description: 'Tap the color you see, not the word.',
  },
  {
    id: 'odd-one-out',
    name: 'Odd One Out',
    category: 'sharpness',
    duration: '1 min',
    durationSec: 60,
    engine: 'OddOneOut',
    description: 'Find the shape that does not belong.',
  },
  {
    id: 'math-sprint',
    name: 'Quick Math Sprint',
    category: 'sharpness',
    duration: '1 min',
    durationSec: 60,
    engine: 'MathSprint',
    description: 'Simple arithmetic, as calm as you can.',
  },
  {
    id: 'word-unscramble',
    name: 'Word Unscramble',
    category: 'sharpness',
    duration: '2 min',
    durationSec: 120,
    engine: 'WordUnscramble',
    description: 'Spell the quiet word from scattered letters.',
  },
  {
    id: 'pattern-completion',
    name: 'Pattern Completion',
    category: 'sharpness',
    duration: '1 min',
    durationSec: 60,
    engine: 'PatternCompletion',
    description: 'What comes next in the sequence?',
  },
  {
    id: 'reaction-tap',
    name: 'Reaction Tap',
    category: 'sharpness',
    duration: '1 min',
    durationSec: 60,
    engine: 'ReactionTap',
    description: 'Tap the moment the dot appears.',
  },
  {
    id: 'coherent-breathing',
    name: 'Coherent Breathing',
    category: 'focus',
    duration: '2 min',
    durationSec: 120,
    engine: 'BreathingOrb',
    description: 'A gentler 5.5-second wave. No hold.',
    props: { variant: 'orb', inhale: 5.5, holdIn: 0, exhale: 5.5, holdOut: 0 },
  },
  {
    id: 'box-breathing',
    name: 'Box Breathing',
    category: 'focus',
    duration: '2 min',
    durationSec: 120,
    engine: 'BreathingOrb',
    description: 'Trace the square: in, hold, out, hold.',
    props: { variant: 'box', inhale: 4, holdIn: 4, exhale: 4, holdOut: 4 },
  },
]

export function getGameById(id) {
  return GAMES.find((game) => game.id === id) ?? null
}

export function gamesByCategory(categoryId) {
  return GAMES.filter((game) => game.category === categoryId)
}

export function getDailyGame(date = new Date()) {
  const seed = Number(
    `${date.getFullYear()}${String(date.getMonth() + 1).padStart(2, '0')}${String(date.getDate()).padStart(2, '0')}`,
  )
  return GAMES[seed % GAMES.length]
}
